// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvqjphzvpfmkoinebvfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2cWpwaHp2cGZta29pbmVidmZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMTcxMjAsImV4cCI6MjA3MDc5MzEyMH0.YaB_S-VpAW_dLxFkAdgfEweUhbBrf09Lp14n857x-jk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});